# Generated by Django 3.1.4 on 2021-01-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210114_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='post',
            field=models.ManyToManyField(related_name='category_post', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='tag_post', to='blog.Post'),
        ),
    ]
