# Generated by Django 3.1.4 on 2021-01-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210115_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='post',
            new_name='posts',
        ),
        migrations.RenameField(
            model_name='post_comment',
            old_name='post',
            new_name='posts',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(related_name='tag_post', to='blog.Post'),
        ),
    ]
