# Generated by Django 3.1.4 on 2021-01-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210115_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='posts',
            field=models.ManyToManyField(to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
